# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 13:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group_product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupproduct',
            name='parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='group_product.GroupProduct'),
        ),
    ]
