# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 11:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id_order', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('qty', models.FloatField(default=0)),
                ('amount', models.FloatField(default=0)),
                ('status', models.CharField(max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id_trans', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('amount', models.FloatField(default=0)),
                ('payment', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='trans',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.Transaction'),
        ),
    ]
