# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 11:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import product.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('unit', '0001_initial'),
        ('group_product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id_product', models.AutoField(primary_key=True, serialize=False)),
                ('name_product', models.CharField(max_length=50, unique=True)),
                ('serial_no', models.IntegerField(default=0)),
                ('img', models.ImageField(blank=True, upload_to=product.models.directory_path)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('describe', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_product', to='group_product.GroupProduct')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_product', to='unit.Unit')),
            ],
        ),
    ]
